# .github/release.yml
changelog:
  categories:
    - title: 🚀 New Features
      labels:
        - enhancement
      include:
        - pattern: '^feat'
    - title: 🐛 Bug Fixes
      labels:
        - bug
      include:
        - pattern: '^fix'
    - title: 🔧 Maintenance
      include:
        - pattern: '^chore|^refactor|^docs'